### ISSUE TITLE
[FEATURE] Neko as a Service

### ISSUE THREAD

**Issue by gbrian** [nurdism/neko#121]
**Is your feature request related to a problem? Please describe.**
We are building free service for ["Navigating internet together"](https://github.com/helppery-com/meetnav-frontend-base/issues/13) on top of Neko. One of the pieces is a service for managing Neko instances on different cloud providers.

**Describe the solution you'd like**
Neko room manager. A service able to manage multiple Neko instances on demand on different cloud providers.

**Describe alternatives you've considered**
Kubernetes, https://dcos.io/, docker swarm,..

**Additional context**
First approach is a naive docker approach with a proxy service but UDP ports are hard to manage as we don't want UDP traffic going always trough proxy server to reduce cloud cost.

All inputs are welcome!

**Comment by m1k1o** [comment]
I wanted to do such thing by myself, some kind of neko orchestrator. Consisting of one controller that would spawn other neko instances on demand.

**Comment by nurdism** [comment]
Hi thank you for submitting a issue about this, but that is a "non goal"  for neko. 

Neko is a single self hosted instance for induvials to spin up and watch a video together. I made the source open so anyone who wants to can adapt the code to w/e they want to. But I do not want to pursue running neko as a distributed service because that would defeat the original goal of having an easy (ish) self hosted remote browser. 

There are other solutions out there similar to neko that are distributed like https://github.com/crybapp
