### ISSUE TITLE
Provide installation instructions for installation without Docker

### ISSUE THREAD

**Issue by Cupcake911** [nurdism/neko#24]
It would be nice to have proper documentation/instructions for running and maintaining neko without docker. Dockerfile is not always very clear.

**Comment by nurdism** [comment]
I'm sorry but neko wasn't designed to run out of a containerized environment, the bare minimum package requirements is in this docker file https://github.com/nurdism/neko/blob/master/Dockerfile and the required packages to build are in https://github.com/nurdism/neko/blob/master/.devcontainer/Dockerfile 

I wont be offering any kinda of support for non-containerized installs as it is a debugging nightmare when it comes to figuring out why different systems/os won't/don't work. Using docker gives you and me the comfort of knowing that the underling system is the same and the issue is the app itself and not some other factor.

**Comment by Cupcake911** [comment]
Thank you for your response, I understand where you're coming from. It's would be a lot more convenient and I wouldn't mind having to deal with figuring out if something doesn't work. It's just that I prefer to use Linux Containers provided by Proxmox rather than docker

**Comment by nurdism** [comment]
I'm not sure how to create Linux Containers myself, I've always used docker. Shouldn't be that hard to setup, you just need a debian based OS, if you look at the docker files, all they contain is bash scripts to install and set up the OS for the application, to build you'd need some extra packages.
